chain = "./chain.json"
base_path = "./node/"

[network]
port = 30301

[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0"

[ui]
port = 8181
interface = "0.0.0.0"

[websockets]
port = 8451
interface = "0.0.0.0"
origins = ["all"]

[ipc]
disable = true
interface = "0.0.0.0"

[account]
password = ["./node.pwd"]

[mining]
engine_signer = "<0xACCOUNT>"
reseal_on_txs = "none"